### ISSUE TITLE
Cannot start the application in MacOs 10.14.2 because of javaFX

### ISSUE THREAD

**Issue by antoniopossidente** [vincenzopalazzo/my-code#2]
I need to install javaFX but I can't find it on https://www.oracle.com/technetwork/java/javafx/downloads/index.html

**Comment by vincenzopalazzo** [comment]
Hello @antoniopossidente ,

I worked a bit on the problem you got and I realized that the path I had undertaken with the installre.sh is not the right one, I found a project to create native installers for javafx and I'm working on it.

I created this application to study the Javafx framework and I think that a limitation in the latest versions of java has been removed from the basic versions of jdk and so now we need to import external modules for execution and compilation with versions over eight ( I'm not sure).

So before getting to compatibility with java versions above 8, I want to release a stable version for version 8 of java, and then focus on portability even on other versions.

I will soon release a version with jre 8 incorporated for those with higher versions of java.

source: [Click me](https://openjfx.io/)

**Comment by vincenzopalazzo** [comment]
Hi @antoniopossidente, 

I have updated the new version of the app, for the update, the version app to Java 11 is more complex and I decided to not support version java >= 11 but I want to test the new installer for MacOS for java11.
so if you test the dmg give me feedback thanks for your support
